// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	base "simple_tiktok/cmd/api/biz/router/base"
	interact "simple_tiktok/cmd/api/biz/router/interact"
	social "simple_tiktok/cmd/api/biz/router/social"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social.Register(r)

	interact.Register(r)

	base.Register(r)
}
