// Code generated by hertz generator.

package feed

import (
	"context"
	feed "simple_tiktok/biz/model/feed"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetVideoList .
// @router /douyin/feed/ [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(feed.FeedResponse)

	c.JSON(consts.StatusOK, resp)
}
