// Code generated by hertz generator.

package Interact

import (
	"github.com/cloudwego/hertz/pkg/app"
	"simple_tiktok/cmd/api/biz/mw"
)

// 干脆再root这里加个鉴权好了。省事哈哈哈
func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.JwtMiddleware()}
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment_ctionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _like_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.IPLimitMiddleware()}
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlikelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
