version: "3.7"
services:
  # MySQL
  mysql:
    image: mysql:latest
#    volumes:
#      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=tiktok
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  #Redis
  redis:
    image: redis:latest
#    restart: always
#    container_name: redis
    ports:
      - "5070:6379"

# Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /

  # ETCD
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "6831:6831"