version: "3.7"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=tiktok
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  #Redis
  redis:
    image: redis:latest
    ports:
      - "5070:6379"

  # Rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
