// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"simple_tiktok/biz/dal"
	"simple_tiktok/biz/redis"
)

func main() {
	dal.Init()
	redis.InitRedis() //sudo service redis-server start
	h := server.Default()

	h.Static("/data/", ".")

	register(h)
	h.Spin()
}
