// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"simple_tiktok/biz/dal"
)

func main() {
	dal.Init()
	h := server.Default()

	h.Static("", "C:/Users/ATXTKS/Pictures")

	register(h)
	h.Spin()
}
