// Code generated by Kitex v0.4.4. DO NOT EDIT.

package interactservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	interact "simple_tiktok/kitex_gen/interact"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	LikeAction(ctx context.Context, request *interact.LikeRequest, callOptions ...callopt.Option) (r *interact.LikeResponse, err error)
	GetLikeList(ctx context.Context, request *interact.LikeListRequest, callOptions ...callopt.Option) (r *interact.LikeListResponse, err error)
	CommentAction(ctx context.Context, request *interact.CommentRequest, callOptions ...callopt.Option) (r *interact.CommentResponse, err error)
	GetCommentList(ctx context.Context, request *interact.CommentListRequest, callOptions ...callopt.Option) (r *interact.CommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractServiceClient struct {
	*kClient
}

func (p *kInteractServiceClient) LikeAction(ctx context.Context, request *interact.LikeRequest, callOptions ...callopt.Option) (r *interact.LikeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, request)
}

func (p *kInteractServiceClient) GetLikeList(ctx context.Context, request *interact.LikeListRequest, callOptions ...callopt.Option) (r *interact.LikeListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLikeList(ctx, request)
}

func (p *kInteractServiceClient) CommentAction(ctx context.Context, request *interact.CommentRequest, callOptions ...callopt.Option) (r *interact.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, request)
}

func (p *kInteractServiceClient) GetCommentList(ctx context.Context, request *interact.CommentListRequest, callOptions ...callopt.Option) (r *interact.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, request)
}
