// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"simple_tiktok/cmd/api/biz/rpc"
)

func main() {
	rpc.Init()
	h := server.Default()
	register(h)
	h.Spin()
}
