init_api:
	hz new -mod simple_tiktok/cmd/api -idl ../../idl/base.thrift

update_api:
	hz update -mod simple_tiktok/cmd/api -idl ../../idl/base.thrift
	hz update -mod simple_tiktok/cmd/api -idl ../../idl/interact.thrift
	hz update -mod simple_tiktok/cmd/api -idl ../../idl/social.thrift