// Code generated by hertz generator.

package user

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"net/http"
	"simple_tiktok/biz/dal"
	"simple_tiktok/pojo"
	"simple_tiktok/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"golang.org/x/crypto/bcrypt"
	"simple_tiktok/biz/model/user"
)

// UserRegister .
// @router /douyin/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	//数据库查一查，有没有这个人
	users, err := dal.FindUserByName(req.Username)
	if err != nil {
		c.JSON(http.StatusOK, utils.H{
			"message": err.Error(),
			"code":    http.StatusBadRequest,
		})
		return
	}
	if len(users) > 0 {
		c.JSON(http.StatusOK, utils.H{
			"message": "user already exists",
			"code":    http.StatusBadRequest,
		})
		return
	}

	resp := new(user.LoginResponse)
	message := ""
	var UserID = int64(0)
	token := ""
	resp.UserID = &UserID
	resp.Token = &token
	resp.StatusMsg = &message

	// 密码加密
	EncodePassword, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	fmt.Println(EncodePassword)

	// 创建实例
	loginUser := pojo.User{
		UserName:      req.Username,
		Password:      string(EncodePassword),
		FollowCount:   0,
		FollowerCount: 0,
	}

	// 执行数据库事务
	if err := dal.CreateUsers(&loginUser); err != nil {
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	UserID = int64(loginUser.ID)

	//颁发token
	token, err = util.GetToken(req.Username)
	if err != nil {
		resp.StatusCode = 1
		c.JSON(consts.StatusBadRequest, resp)
	}
	c.JSON(consts.StatusOK, resp)
}

// UserLogin .
// @router /douyin/user/login/ [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LoginResponse)
	message := ""
	var UserID = int64(0)
	token := ""
	resp.UserID = &UserID
	resp.Token = &token
	resp.StatusMsg = &message

	//数据库查一查，有没有这个人
	users, err := dal.FindUserByName(req.Username)
	if err != nil {
		resp.StatusCode = 1
		message = "请求错误"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	if len(users) == 0 {
		resp.StatusCode = 1
		message = "没有此用户"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	// 密码认证
	if err := bcrypt.CompareHashAndPassword([]byte(users[0].Password), []byte(req.Password)); err != nil {
		resp.StatusCode = 1
		message = "用户名或密码错误"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	token, err = util.GetToken(req.Username)
	if err != nil {
		resp.StatusCode = 1
		message = "颁发token失败"
		c.JSON(consts.StatusBadRequest, resp)
	}
	resp.StatusCode = 0
	message = "登录成功"
	UserID = int64(users[0].ID)
	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /douyin/user/ [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserInfoResponse)
	var message = ""
	resp.StatusMsg = &message

	//数据库查一查，有没有这个人
	users, err := dal.FindUserByID(req.UserID)
	if err != nil {
		resp.StatusCode = 1
		message = "请求错误"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	if len(users) == 0 {
		resp.StatusCode = 1
		message = "没有此用户"
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	resp.StatusCode = 0
	message = "请求成功"
	userInfo := &user.UserInfo{
		ID:            int64(users[0].ID),
		Name:          users[0].UserName,
		FollowCount:   users[0].FollowCount,
		FollowerCount: users[0].FollowerCount,
		IsFollow:      false,
	}
	resp.User = userInfo
	c.JSON(consts.StatusOK, resp)
}
