// Code generated by Kitex v0.4.4. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	social "simple_tiktok/kitex_gen/social"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, request *social.FollowRequest, callOptions ...callopt.Option) (r *social.FollowResponse, err error)
	GetFollowList(ctx context.Context, request *social.FollowingListRequest, callOptions ...callopt.Option) (r *social.FollowingListResponse, err error)
	GetFollowerList(ctx context.Context, request *social.FollowerListRequest, callOptions ...callopt.Option) (r *social.FollowerListResponse, err error)
	GetFriendList(ctx context.Context, request *social.FriendListRequest, callOptions ...callopt.Option) (r *social.FriendListResponse, err error)
	MessageChat(ctx context.Context, req *social.MessageChatReq, callOptions ...callopt.Option) (r *social.MessageChatResp, err error)
	MessageAction(ctx context.Context, req *social.MessageActionReq, callOptions ...callopt.Option) (r *social.MessageActionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) FollowAction(ctx context.Context, request *social.FollowRequest, callOptions ...callopt.Option) (r *social.FollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, request)
}

func (p *kSocialServiceClient) GetFollowList(ctx context.Context, request *social.FollowingListRequest, callOptions ...callopt.Option) (r *social.FollowingListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowList(ctx, request)
}

func (p *kSocialServiceClient) GetFollowerList(ctx context.Context, request *social.FollowerListRequest, callOptions ...callopt.Option) (r *social.FollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerList(ctx, request)
}

func (p *kSocialServiceClient) GetFriendList(ctx context.Context, request *social.FriendListRequest, callOptions ...callopt.Option) (r *social.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendList(ctx, request)
}

func (p *kSocialServiceClient) MessageChat(ctx context.Context, req *social.MessageChatReq, callOptions ...callopt.Option) (r *social.MessageChatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageChat(ctx, req)
}

func (p *kSocialServiceClient) MessageAction(ctx context.Context, req *social.MessageActionReq, callOptions ...callopt.Option) (r *social.MessageActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageAction(ctx, req)
}
