// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	favorite "simple_tiktok/biz/router/favorite"
	feed "simple_tiktok/biz/router/feed"
	publish "simple_tiktok/biz/router/publish"
	user "simple_tiktok/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	favorite.Register(r)

	publish.Register(r)

	feed.Register(r)

	user.Register(r)
}
